### ISSUE TITLE
PCIe ethernet card

### ISSUE THREAD

**Issue by peteretep** [SmartRoboticSystems/ros_powerlink#1]
Hello, 
I am investigating ros_powerlink and am developing on a laptop that uses a pcie based ethernet adaptor, using ubuntu 16.04
I tried to compile the `drv_kernelmod_pcie` drivers but was unsuccessful with this error message:

```
/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.c: In function ‘plkIntfIoctl’:
/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.c:567:17: error: implicit declaration of function ‘copy_to_user’ [-Werror=implicit-function-declaration]
             if (copy_to_user((void __user*)arg_p, &instance_l.bufPageOffset, sizeof(ULONG)))
                 ^
/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.c: In function ‘postEventFromUser’:
/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.c:843:9: error: implicit declaration of function ‘copy_from_user’ [-Werror=implicit-function-declaration]
     if (copy_from_user(&event, (const void __user*)arg_p, sizeof(tEvent)))
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:308: recipe for target '/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.o' failed
make[4]: *** [/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build/src/main.o] Error 1
Makefile:1550: recipe for target '_module_/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build' failed
make[3]: *** [_module_/home/peter/openPOWERLINK_V2.6.2/drivers/linux/drv_kernelmod_pcie/build] Error 2
CMakeFiles/oplkmnpcieintf.dir/build.make:75: recipe for target 'oplkmnpcieintf.ko' failed
make[2]: *** [oplkmnpcieintf.ko] Error 2
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/oplkmnpcieintf.dir/all' failed
make[1]: *** [CMakeFiles/oplkmnpcieintf.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
I then compiled the `drv_deamon_pcap` driver instead, which seemed to work.

I moved onto ROS setup, running `catkin_make`, I am getting the following error messages:

```
CMakeFiles/ros_powerlink.dir/src/main.cpp.o: In function `main':
main.cpp:(.text.startup+0x3d9): undefined reference to `selectPcapDevice'
/home/peter/openPOWERLINK_V2.6.2/stack/lib/linux/x86_64/liboplkcn.a(edrv-pcap_linux.c.o): In function `startPcap':
edrv-pcap_linux.c:(.text+0x116): undefined reference to `pcap_create'
edrv-pcap_linux.c:(.text+0x126): undefined reference to `pcap_set_snaplen'
edrv-pcap_linux.c:(.text+0x133): undefined reference to `pcap_set_promisc'
edrv-pcap_linux.c:(.text+0x140): undefined reference to `pcap_set_immediate_mode'
edrv-pcap_linux.c:(.text+0x148): undefined reference to `pcap_activate'
/home/peter/openPOWERLINK_V2.6.2/stack/lib/linux/x86_64/liboplkcn.a(edrv-pcap_linux.c.o): In function `workerThread':
edrv-pcap_linux.c:(.text+0x1ae): undefined reference to `pcap_setdirection'
edrv-pcap_linux.c:(.text+0x1d0): undefined reference to `pcap_loop'
/home/peter/openPOWERLINK_V2.6.2/stack/lib/linux/x86_64/liboplkcn.a(edrv-pcap_linux.c.o): In function `edrv_init':
edrv-pcap_linux.c:(.text+0x28a): undefined reference to `pcap_setdirection'
/home/peter/openPOWERLINK_V2.6.2/stack/lib/linux/x86_64/liboplkcn.a(edrv-pcap_linux.c.o): In function `edrv_exit':
edrv-pcap_linux.c:(.text+0x3ce): undefined reference to `pcap_breakloop'
edrv-pcap_linux.c:(.text+0x3f4): undefined reference to `pcap_close'
/home/peter/openPOWERLINK_V2.6.2/stack/lib/linux/x86_64/liboplkcn.a(edrv-pcap_linux.c.o): In function `edrv_sendTxBuffer':
edrv-pcap_linux.c:(.text+0x529): undefined reference to `pcap_sendpacket'
collect2: error: ld returned 1 exit status

```

Any pointers would be great, thank you!

**Comment by durovsky** [comment]
Hello Peter, not sure but the missing copy_to_user issue might be related to latest changes in kernel. It might be worth trying to build the stack on older kernels. Try 4.4 or similar. There is a great utility for kernel juggling named UKUU - http://www.teejeetech.in/p/ukuu-kernel-upgrade-utility.html

**Comment by peteretep** [comment]
Thanks for the response - I tried to build on 4.4 and am getting the same errors.
`uname -r
4.4.120-0404120-generic
`

Any other ideas?
Thanks..

**Comment by peteretep** [comment]
Thanks for the help - I think I've managed to get up and running using the pcap drivers.
Still a couple of sudo issues but on the right track now.
